name: Download Perfect Book from MEGA

on:
  workflow_dispatch:

jobs:
  mega-book:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install megatools
        run: |
          sudo apt-get update
          sudo apt-get install -y megatools

      - name: Create folder
        run: mkdir -p engines

      - name: Download from MEGA (public file)
        run: |
          echo "📥 Downloading MEGA file..."
          megadl 'https://mega.nz/file/F60VXIzL#UXOad32h53pHN7E_4arBzwkbKQtD2kezqOo7kOPAlOA' --path engines/perfect_book.bin

      - name: Validate book file
        run: |
          FILE="engines/perfect_book.bin"
          if [ ! -f "$FILE" ]; then
            echo "❌ File not found!"
            exit 1
          fi

          SIZE=$(stat -c %s "$FILE")
          echo "File size: $SIZE bytes"

          REM=$((SIZE % 16))
          if [ "$SIZE" -lt 16384 ]; then
            echo "❌ Too small (<16KB)"
            exit 1
          elif [ "$REM" -ne 0 ]; then
            echo "⚠️ Size not multiple of 16, trimming $REM bytes..."
            head -c $((SIZE - REM)) "$FILE" > "${FILE}.fixed"
            mv "${FILE}.fixed" "$FILE"
          else
            echo "✅ File size is valid"
          fi

      - name: Commit if valid
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add engines/perfect_book.bin
          git commit -m "Add perfect Polyglot book from MEGA"
          git push
