name: Download Ruy Lopez Book

on:
  workflow_dispatch:

jobs:
  download-book:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create engines folder
        run: mkdir -p engines

      - name: Download book from PixelDrain
        run: |
          echo "Downloading book..."
          curl -L --retry 5 --retry-delay 3 "https://pixeldrain.com/api/file/gQziifHp?download" -o engines/ruylopez_book.bin
          echo "Download complete"

      - name: Verify file exists and is large enough
        run: |
          FILE=engines/ruylopez_book.bin
          if [ ! -f "$FILE" ]; then
            echo "❌ Book file does not exist!"
            exit 1
          fi

          SIZE=$(stat -c%s "$FILE")
          echo "Downloaded file size: $SIZE bytes"

          if [ "$SIZE" -lt 16000 ]; then
            echo "❌ Book file seems incomplete or corrupt (too small)"
            exit 1
          fi

          echo "✅ Book downloaded successfully and looks valid"

      - name: Show file info
        run: ls -lh engines/ruylopez_book.bin
